Stac-13817: upgrade docker agent
StackVista/stackstate-agent pull request #355
Opened 2021-08-06 11:40 UTC by vishalxebia

### Step 1: Link to Jira issue

### Step 2: Description of changes

### Step 3: Did you add / update tests for your changes in the right area?
- [ ] Unit/Component test
- [ ] Integration test
- [ ] E2E/Molecule test

### Step 4: I'm confident that everything is properly tested:
I got a PO / QA Approval by:
- [ ] Name

### Step 5: Did you add release notes describing the changes you made?
- [ ] Yes

### Step 6: Can we ship this feature to production?
- [ ] Yes, I'm proud of my work. Ship it! :ship:

2021-08-06 12:51 UTC, LouisParkin commented on requirements.txt
>  requests==2.23.0
`requests==2.25.0`

2021-08-06 12:55 UTC, LouisParkin commented on Dockerfiles/agent/Dockerfile
> +FROM ubuntu:21.04 as extract
Why Ubuntu (move away from Debian), and not just use Debian Bullseye?
https://hub.docker.com/layers/debian/library/debian/bullseye-slim/images/sha256-fd9bc56e83c76803d355ddbe0a4e18aae08f4ee16d05a6fafb843ee90cc0104c?context=explore

2021-08-06 12:56 UTC, LouisParkin commented on Dockerfiles/agent/Dockerfile
> +FROM ubuntu:21.04 as extract
`docker pull debian:bullseye-slim`

2021-08-06 12:58 UTC, LouisParkin commented on requirements.txt
>  requests==2.23.0
And please add `urllib3==1.26.5`

2021-08-31 12:43 UTC, julianosk requested changes

2021-08-31 12:43 UTC, julianosk commented on Dockerfiles/cluster-agent/Dockerfile
> +FROM ubuntu:20.04 as builder
Pull from StackState artifactory

2021-08-31 12:43 UTC, julianosk commented on omnibus/config/software/python3.rb
> +    # security patches
Add a comment to remove this patch once python 3 is updated to 3.8.11, 3.9 or 3.10

2021-08-31 12:43 UTC, julianosk commented on omnibus/config/software/stackstate-agent-integrations-py2.rb
> +#       patch :source => "jpype_0_7.patch", :target => "#{python_2_embedded}/Lib/site-packages/jaydebeapi/__init__.py"
Remove these commented lines

2021-08-31 12:43 UTC, julianosk commented on omnibus/config/software/stackstate-agent-integrations-py3.rb
> +#     if windows?
Remove

2021-08-31 12:43 UTC, julianosk commented on stackstate-deps.json
> +  "STACKSTATE_INTEGRATIONS_VERSION": "stac-13817-upgrade-docker-agent",
Update to master

2021-09-06 08:24 UTC, julianosk approved these changes
LGTM

2021-09-06 10:30 UTC, merged