STAC-15121 - Fix pipeline
StackVista/stackstate-agent pull request #403
Opened 2021-12-07 10:03 UTC by julianosk

### Step 1: Link to Jira issue

### Step 2: Description of changes

### Step 3: Did you add / update tests for your changes in the right area?
- [ ] Unit/Component test
- [ ] Integration test
- [ ] E2E/Molecule test

### Step 4: I'm confident that everything is properly tested:
I got a PO / QA Approval by:
- [ ] Name

### Step 5: Did you add release notes describing the changes you made?
- [ ] Yes

### Step 6: Can we ship this feature to production?
- [ ] Yes, I'm proud of my work. Ship it! :ship:

2021-12-08 09:30 UTC, hruhek requested changes
Two changes for PyPI url

2021-12-08 09:30 UTC, hruhek commented on local_build.sh
> +            -e ARTIFACTORY_PYPI_URL="artifactory.tooling.stackstate.io/artifactory/api/pypi/pypi-local" \
This should be `artifactory.tooling.stackstate.io/artifactory/api/pypi/pypi-virtual`.

2021-12-08 09:30 UTC, hruhek commented on .assistance/Vagrantfile
> +    echo "export ARTIFACTORY_PYPI_URL=artifactory.tooling.stackstate.io/artifactory/api/pypi/pypi-local" >> /home/vagrant/.env
This should be `artifactory.tooling.stackstate.io/artifactory/api/pypi/pypi-virtual`

2021-12-08 12:38 UTC, hruhek requested changes

2021-12-08 12:38 UTC, hruhek commented on .gitlab-scripts/setup_artifactory.sh
> +echo "extra-index-url = https://$artifactory_user:$artifactory_password@$ARTIFACTORY_PYPI_URL/simple" >> ~/.pip/pip.conf
`/simple` is already included in `ARTIFACTORY_PYPI_URL`

2021-12-08 12:44 UTC, hruhek approved these changes
Looks OK now :)

2021-12-09 12:48 UTC, Q69K commented on .assistance/Vagrantfile
> +    echo "export artifactory_password=ZPxcNe6dXZmGmCz3" >> /home/vagrant/.env
```suggestion
```

2021-12-13 14:23 UTC, Q69K commented on tasks/go.py
> +            "golangci-lint run -c -v .golangci.yml --build-tags '{}' {}".format(" ".join(tags), "{}/...".format(target)),
```suggestion
            "golangci-lint run -v -c .golangci.yml --build-tags '{}' {}".format(" ".join(tags), "{}/...".format(target)),
```

2021-12-13 14:48 UTC, Q69K commented on .gitlab-ci-agent.yml
>    retry:
```suggestion
  tags:
    - sts-k8s-xl-runner
  retry:
```

2021-12-13 14:49 UTC, Q69K commented on .gitlab-ci-agent.yml
>    rules:
```suggestion
  tags:
    - sts-k8s-xl-runner
  rules:
```

2021-12-13 14:49 UTC, Q69K commented on .gitlab-ci-cluster-agent.yml
>    retry:
```suggestion
  tags:
    - sts-k8s-xl-runner
  retry:
```

2021-12-15 12:33 UTC, closed without merging